

const CategoryEnum = Object.freeze({
    0: "Restaurante Comida Española",
    1: "Restaurante Chino",
    2: "Cervecería",
    3: "Pub",
    4: "Cafetería",
    5: "Heladería",
    6: "Pastelería - Panadería",
    7: "Restaurante Italiano",
    8: "Restaurante Americano",
    9: "Pizzería",
    10: "Hamburguesería",
    11: "Restaurante Japonés",
    12: "Restaurante Peruano",
    13: "Restaurante Argentino",
    14: "Restaurante Venezolano",
    15: "Restaurante Colombiano",
    16: "Restaurante Mexicano",
    17: "Brasería",
    18: "Restaurante Indio",
    19: "Restaurante Tailandés",
    20: "Restaurante Turco",
    21: "Restaurante Caribeño",
    22: "Restaurante Ecuatoriano",
    23: "Restaurante Brasileño",
    24: "Restaurante Africano",
    25: "Restaurante Libanés",
    26: "Restaurante Marroquí",
    27: "Restaurante Vietnamita",
    28: "Restaurante Griego",
    29: "Restaurante Portugués",
    30: "Restaurante Árabe",
    31: "Restaurante Asturiano",
    32: "Restaurante Comida Rápida",
    32: "Restaurante Vegetariano",
    33: "Marisquería",
    34: "Comida casera para llevar",
    35: "Quesería",
    36: "Vinoteca",

  });
  
  export default CategoryEnum;
  